### ISSUE TITLE
 Unable to retrieve AudioTrack pointer for stop()

### ISSUE THREAD

**Issue by dongliwu520** [martin-niceyang/AndroidAudio#3]
首先感觉作者的开源 最近在使用该库的时候发现了一些问题 能看一下问题吗？

D/AudioTrack: stop(sessionID=62777)
D/AudioTrack: stop(7373): prior state:STATE_ACTIVE
D/AudioTrack: stop(7373): called with 169608 frames delivered
D/AudioTrack: stop(sessionID=62777)
D/AudioTrack: stop(7373): prior state:STATE_STOPPED
D/AudioTrack: ~AudioTrack(sessionID=62777)
W/System.err: java.lang.IllegalStateException: Unable to retrieve AudioTrack pointer for stop()
W/System.err:     at android.media.AudioTrack.native_stop(Native Method)
W/System.err:     at android.media.AudioTrack.stop(AudioTrack.java:2738)
W/System.err:     at com.martin.audiolib.play.OpusAudioPlayer.releaseAudioTrack(OpusAudioPlayer.kt:266)
W/System.err:     at com.martin.audiolib.play.OpusAudioPlayer.cleanUp(OpusAudioPlayer.kt:249)
W/System.err:     at com.app.tideswing.common.recoder.AudioPlayManager.play(AudioPlayManager.java:64)
W/System.err:     at com.app.tideswing.ui.view.ActivitiesDetailFragment.onPlayAudioMessage(ActivitiesDetailFragment.java:1023)
 D/AudioTrack: stop(sessionID=62777)
D/AudioTrack: stop(7373): prior state:STATE_STOPPED
D/AudioTrack: set(sessionId=0)
D/AudioTrack: set(): streamType -1, sampleRate 48000, format 0x1, channelMask 0x1, frameCount 1924, flags #0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1
W/BpBinder: PerfMonitor binderTransact :  time=365ms interface=android.media.IAudioFlinger code=1
W/AudioTrack: Use of stream types is deprecated for operations other than volume control
W/AudioTrack: See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case

**Comment by hloMartin** [comment]
额，这个应该不会影响正常使用的。
播放前做了一次清理，这个异常是主动捕获的，只是我把它打印出来了，不会影响正常播放。
你如果不想看到这个异常，可以把库考过去，修改一下代码，不打印就好了。
